"""adding non nullable to columns

Revision ID: e73672288371
Revises: 133e7ef2dc7d
Create Date: 2020-05-12 12:43:58.035568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e73672288371'
down_revision = '133e7ef2dc7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('videos', 'author',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('videos', 'title',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('videos', 'videoID',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('videos', 'videoID',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('videos', 'title',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('videos', 'author',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    # ### end Alembic commands ###
